CREATE table LOG(
    USER_ID INTEGER,
    TIME DATETIME,
    BET NUMERIC(10, 2),
    WIN NUMERIC(10, 2)
);

CREATE table USERS(
    USER_ID INTEGER PRIMARY KEY,
    EMAIL VARCHAR,
    GEO VARCHAR
);
